/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.app;

import static com.conversor.app.Util.*;


/**
 *
 * @author jaime
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    
    
    public  About() {
        initComponents();
        setIconImage(IconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        challengueOne = new javax.swing.JLabel();
        backEnd = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        version1 = new javax.swing.JLabel();
        version4 = new javax.swing.JLabel();

        setTitle("About");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        challengueOne.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        challengueOne.setForeground(new java.awt.Color(51, 51, 51));
        challengueOne.setText("Challengue ONE");
        jPanel1.add(challengueOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        backEnd.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        backEnd.setForeground(new java.awt.Color(0, 102, 51));
        backEnd.setText("Back - End Java ");
        jPanel1.add(backEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        about.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        about.setForeground(new java.awt.Color(51, 51, 51));
        about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about.setText("About");
        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, -1));

        name.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Conversor de unidades");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, -1));

        version.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        version.setForeground(new java.awt.Color(51, 51, 51));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("Version: 1.0.0");
        version.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, -1));

        version1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        version1.setForeground(new java.awt.Color(51, 51, 51));
        version1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version1.setText("Developed by: Jaime Vargas");
        version1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(version1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, -1));

        version4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        version4.setForeground(new java.awt.Color(51, 51, 51));
        version4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version4.setText("Release date: 19/07/2023");
        version4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(version4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel backEnd;
    private javax.swing.JLabel challengueOne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel version;
    private javax.swing.JLabel version1;
    private javax.swing.JLabel version4;
    // End of variables declaration//GEN-END:variables
}
